### ISSUE TITLE
No module named 'ah_bootstrap' - again

### ISSUE THREAD

**Issue by mommermi** [NASA-Planetary-Science/sbpy#104]
I merged Miguel's `astropy_helpers` update (#95) since there where no build issues, but now all the Travis-CI builds seem to break. See here: https://travis-ci.org/NASA-Planetary-Science/sbpy/jobs/481600991

The problem seems to be `ah_bootstrap` again - we had this issue in #1 and solved it by manually copying `ah_boostrap.py` into the root directory. However, it seems that this is actually triggered when `astroquery` is being installed. I know that they are currently having build issues, too. Should we wait and see if they can fix it, or is there anything we can do about this?

**Comment by mommermi** [comment]
Hmm. Maybe. I intentionally installed the master branch, since v0.3.9 did not include some of the recent changes to `astroquery` like `jplsbdb`. I'll try that tonight.

**Comment by migueldvb** [comment]
Ah OK, then it would be better to keep the master branch of astroquery until the next release. Interestingly nothing has changed in `ah_bootstrap.py` between releases 2.0.7 and 2.0.8... Perhaps we can revert the changes in #95 to fix the build issues?

**Comment by mommermi** [comment]
This problem has disappeared with the new Travis-CI setup.
