### ISSUE TITLE
open v0.1 issues 

### ISSUE THREAD

**Issue by mommermi** [NASA-Planetary-Science/sbpy#135]
This is a to-do list for open items before we can release v0.1 and submit to JOSS:

* [x] finalize and merge `sbpy.photometry` updates (#134, @jianyangli)
* [x] finalize and merge `sbpy.activity` updated (#129, @mkelley)
* [x] update `sbpy.spectroscopy` to follow rules (@migueldvb)

If there is anything I did not mention here, simply reply and I will add it to the list.

**Comment by mkelley** [comment]
Does anything besides submission need to be done for #85 ?

**Comment by mommermi** [comment]
Based on https://joss.readthedocs.io/en/latest/submitting.html, we submit to JOSS, work their review comments into the repo, then create an archived version at zenodo, and that's it. 

So right now, it's really just bringing the code into a good shape...

**Comment by gianninapr** [comment]
@migueldvb I'll help you update `sbpy.spectroscopy` to follow the rules.

**Comment by mommermi** [comment]
@migueldvb @gianninapr what is the status of `sbpy.spectroscopy`? Any chance that it's up-to-date any time soon? If not, I propose that we go ahead and submit to JOSS what we have now.

**Comment by gianninapr** [comment]
@mommermi I can try my best to fix the problems I'm facing with the changes by the end of today. If I don't achieve that you can feel free to go ahead and submit to JOSS after tomorrow. I don't know about @migueldvb parts

**Comment by migueldvb** [comment]
@gianninapr I'll open a pull request using the Ephem/Orbit/Phys objects in spectroscopy and will give your write access to the branch.

**Comment by gianninapr** [comment]
Sounds good. I'll be looking out for your PR and then I'll commit to it what I have @migueldvb

**Comment by gianninapr** [comment]
Pull requests #140 and #141 take care of the last item that needs to be checked out for this!

**Comment by mommermi** [comment]
@NASA-Planetary-Science/sbpy I will release v0.1 and submit our JOSS proposal tomorrow (May 1, noon, MST), unless somebody disagrees. Thanks, guys!
