### ISSUE TITLE
setup.py should not manually read metadata from setup.cfg

### ISSUE THREAD

**Issue by Juanlu001** [NASA-Planetary-Science/sbpy#151]
See https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=setup.cfg#configuring-setup-using-setup-cfg-files

For example: https://github.com/poliastro/poliastro/blob/8c3fdfcfbc02be18ce3c9b7a1b6703a818d1288a/setup.py#L8

**Comment by bsipocz** [comment]
@Juanlu001 - sbpy uses the astropy package template, including the setup files and as such comes with a lot of historical etc baggage (e.g. supporting older setuptools versions, providing a template to support both python2 and python3 versions, etc), yet for overall maintenance it would be easier for everyone involved to minimize divergence from the template unless there are good reasons for it. Thus I would suggest removing this item from the list of issues for the joss review.

As of the package template, we're about to tag a new version that has reworked the setup infrastructure and ultimately makes setuptools 30.3 the minimum required version.

**Comment by Juanlu001** [comment]
Fair enough! Let's not make this a blocker. Looking forward to the new template :)

**Comment by mommermi** [comment]
Thanks, @bsipocz  and @Juanlu001!
