### ISSUE TITLE
Tag and version mismatch

### ISSUE THREAD

**Issue by Juanlu001** [NASA-Planetary-Science/sbpy#152]
A `v0.1` tag exists, however

https://github.com/NASA-Planetary-Science/sbpy/blob/v0.1/setup.cfg#L35

**Comment by Juanlu001** [comment]
That's probably the reason why the docs still point to `v0.0.dev604`

**Comment by mommermi** [comment]
this has been fixed here: f151802

**Comment by mkelley** [comment]
OK to close this one?

**Comment by Juanlu001** [comment]
Closing!
