### ISSUE TITLE
improve documentation for contributions

### ISSUE THREAD

**Issue by mommermi** [NASA-Planetary-Science/sbpy#155]
it would be nice to describe these steps, even if they are obvious to experienced developers, in https://sbpy.readthedocs.io/en/latest/contributing.html

**Comment by bsipocz** [comment]
You're welcome to reuse the astropy contribution guide (in case you follow that, or just gut out the things you don't need). In e.g. astroquery we just list what we do on top of that guide (see e.g https://github.com/astropy/astroquery/blob/master/CONTRIBUTING.rst)

**Comment by mommermi** [comment]
Perfect, thanks, @bsipocz!

**Comment by mommermi** [comment]
I updated the guidelines here: b8c9a84

Please let me know if you suggest anything else to be mentioned here.
