### ISSUE TITLE
bib clean-up 

### ISSUE THREAD

**Issue by mommermi** [NASA-Planetary-Science/sbpy#176]
Currently, there is a lot of garbage in the `bib` results:

> INFO: Thank you for using sbpy.  Your session results were based on:
> sbpy.bib.tests.test_bib.force:
>   method:
>       Newton 1687, Philosophiae Naturalis Principia Mathematica. Auctore Js. Newton
> test1:
>   track_this:
>       bibcode1
>   software:
>       bibcode2
>   track_this_too:
>       bibcode
> test2:
>   software:
>       bibcode
> test3:
>   track_this:
>       bibcode
>   software:
>       bibcode
> spectroscopy:
>   fdsa:
>       asdf
>   Dust-free template spectrum of Bohlin 2014:
>       Bohlin 2014, The Astronomical Journal, Vol 147, 6, 127
>   E490-00a (2014) reference solar spectrum (Table 3):
>       doi:10.1520/E0490
> sbpy.data.Ephem.from_horizons:
>   data service:
>       Giorgini, Yeomans, Chamberlin et al. 1996, AAS/Division for Planetary Sciences Meeting Abstracts #28, 25.04
> sbpy.data.Phys.from_sbdb:
>   data service url:
>       https://ssd.jpl.nasa.gov/sbdb.cgi
> activity.dust.Afrho:
>   model:
>       Ahearn, Schleicher, Millis et al. 1984, The Astronomical Journal, Vol 89, 579
> activity.dust.Efrho:
>   model:
>       Kelley, Fernández, Licandro et al. 2013, Icarus, Vol 225, 1, 475
> activity.dust.phase_HalleyMarcus:
>   Halley-Marcus phase function:
>       Schleicher & Bair 2011, The Astronomical Journal, Vol 141, 6, 177
>   Halley phase function:
>       Schleicher, Millis & Birch 1998, Icarus, Vol 132, 2, 397
>   Marcus phase function:
>       Marcus 2007, International Comet Quarterly, Vol 29, 39
>  [sbpy.bib.core]

Everybody, please check your submodules.

**Comment by mkelley** [comment]
Looks like at least one bib test is not not leaving tracking disabled.  I'll take care of it.

**Comment by mkelley** [comment]
I think this is fixed.  I haven't seen any extra lines after the tests.
