### ISSUE TITLE
Revise documentation based on review comments.

### ISSUE THREAD

**Issue by mommermi** [NASA-Planetary-Science/sbpy#187]
Overall documentation
-----------------------------

Review comments provided in pdf that was sent around:
* [x] MM done
* [x] MSK done
* [x] MdVB
* [x] JYL done
* [x] GG done

Status page
---------------

Is [it](https://sbpy.readthedocs.io/en/latest/status.html) up-to-date?
* [x] MM done
* [x] MSK done
* [x] MdVB
* [x] JYL done
* [x] GG done

Submodule Description
------------------------------
Is [it](https://sbpy.readthedocs.io/en/latest/about.html#module-structure) up-to-date?
* [x] MM done
* [x] MSK done
* [x] MdVB
* [x] JYL done
* [x] GG done

**Comment by mommermi** [comment]
@mkelley @migueldvb @jianyangli  @gianninapr just a reminder to track your progress here. Thanks!

**Comment by mkelley** [comment]
#212

**Comment by jianyangli** [comment]
#217
