### ISSUE TITLE
Verify existing notebooks: do they run?  are they still useful?

### ISSUE THREAD

**Issue by mkelley** [NASA-Planetary-Science/sbpy#209]
Opening this issue as a reminder for all and to mark it for milestone v0.2.

**Comment by mkelley** [comment]
Notebooks to check:

- [ ] photometry/integrated_phasefunc.ipynb
- [ ] data/Orbit.ipynb
- [ ] data/General_concepts.ipynb
- [ ] data/Phys.ipynb
- [ ] data/Names.ipynb
- [ ] data/Ephem.ipynb
- [ ] activity/productionrates.ipynb
- [ ] activity/dust.ipynb
- [ ] activity/gas.ipynb
- [ ] activity/jplspec.ipynb

**Comment by mkelley** [comment]
PRs for dust and gas submitted.

**Comment by gianninapr** [comment]
I want to add stuff to jplspec one, will do so Monday

**Comment by gianninapr** [comment]
@mommermi 

data/General_concepts needs to be updated to not use `add_column` anymore, `apply` is the new one.

All other notebooks seem to be running alright if pyoorb is installed. 

I have opened a pull request in sbpy-tutorials with the addition of the pyradex code example into productionrate.ipynb, and with the addition of `from_jplspec` examples in data/phys.ipynb

**Comment by gianninapr** [comment]
@jianyangli photometry/integrated_phasefunc.ipynb isn't really working well for me. Of the highlight errors I get are the following, in order of occurrence:

```
AttributeError: 'LinearPhaseFunc' object has no attribute 'geoalb'
'HG' object has no attribute 'geoalb'
'HG' object has no attribute 'mag'
ImportError: cannot import name 'DiskIntegratedModelClass'
```

**Comment by mommermi** [comment]
@jianyangli Did you have a chance to check your notebook?

**Comment by jianyangli** [comment]
Working on it now.

**Comment by jianyangli** [comment]
Updated photometry notebook merged.

**Comment by mommermi** [comment]
Thanks, guys, for working on this!
