### ISSUE TITLE
pyradex testing issues

### ISSUE THREAD

**Issue by gianninapr** [NASA-Planetary-Science/sbpy#215]
See #189 

Due to the heavy dependency of this code on pyradex, we will have to find a way to work around remote tests and Travis not being able to import pyradex within the environment. Since the pyradex implementation is a big chunk of code, codecov isn't happy that we're not testing the pyradex implementation. Maybe monkey patching is an option? I'm unfamiliar with how to monkey patch in python and will have to learn more about that.

The tests work very well locally and they are currently commented out with information attached of when they were last run locally and by who.

**Comment by migueldvb** [comment]
In the remote test that needs `pyradex` you can try importing it in the beginning of the function and skip the test if the wrapper is not available.

```
    try:
        import pyradex
    except ImportError:
        ...
```

The  test is passing fine locally for me as well. Perhaps if you uncomment `test_Haser_pyradex` with that modification the code coverage will increase but I'm not sure. I think there is not much more that can be done unfortunately.

**Comment by mommermi** [comment]
Let me reopen this for now as a reminder (to myself): maybe it is possible to monkeypatch pyradex and at least to test the functionality implemented in sbpy...
