### ISSUE TITLE
Missing alphabet from declared string within sbpy.data.names. Unpacking returns incorrect value

### ISSUE THREAD

**Issue by astroboy8** [NASA-Planetary-Science/sbpy#270]
**Incomplete alphabet in declared string, used for packing and unpacking Asteroid designations**
The string 'pkd' declared within class Names is missing the alphabet 'j', instead 'f' is repeated twice.

**Original code obtained from sbpy**
# class Names():
    """Class for parsing target identifiers. The functions in this class will
    identify designation, name strings, and number for both comets and
    asteroids. It also includes functionality to distinguish between comet and
    asteroid identifiers."""

    # packed numbers translation string
    pkd = ('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
           'abcdefghifklmnopqrstuvwxyz')

**Correction made**
# class Names():
    """Class for parsing target identifiers. The functions in this class will
    identify designation, name strings, and number for both comets and
    asteroids. It also includes functionality to distinguish between comet and
    asteroid identifiers."""

    # packed numbers translation string
    pkd = ('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
           'abcdefghijklmnopqrstuvwxyz')

**The string 'pkd' now has the right alphabet sequence**

**What did you expect?**
The code was meant to unpack asteroid designations from the Minor Planet Center data. 

**What did really happen?**
The unpacking returned an integer value for all the designations containing 'j' in it. The integer value produces an error when used to obtain observational data from MPC.

**OS and astropy version**
operating system and version: Win10 Pro
astropy version: 3.2.3

**Comment by mkelley** [comment]
Thanks for the bug report, @astroboy8 .  I've referred to the [documentation](https://www.minorplanetcenter.net/iau/info/PackedDes.html) and I agree that this appears to be an error.  I'll make a fix now.
