### ISSUE TITLE
Possible bug in Photometry, Disk-integrated phase functions

### ISSUE THREAD

**Issue by anttipenttila** [NASA-Planetary-Science/sbpy#282]
There is either a bug in the disk-integrated phase functions in the photometry module, or then I don't understand how to use them properly. The problem is simple, and you can see it from the example code that follows. In short, with all other than the HG-phase function, the 'evaluate' method returns different (and wrong) values compared to the one returned by the model object that is initialized with given parameter values. The code showing this behavior is like this:

Win 10, 64-bit
sbpy version: 0.3.dev1087'
astropy version: 4.2.1
numpy version: 1.19.5

```python
import numpy as np
import astropy.units as u
import sbpy
from sbpy.photometry import HG, HG1G2, HG12, HG12_Pen16

# Testing HG-model
print("HG-model")
hp = 15*u.mag
gp = 0.15
phase=10.0*u.deg
HGm = HG(H=hp, G=gp)
print(HGm(phase))
print(HG.evaluate(phase, hh=hp, gg=gp))

# Testing HG1G2-model
print("HG1G2-model")
hp = 15*u.mag
g1p = 0.15
g2p = 0.5
phase=10.0*u.deg
HG1G2m = HG1G2(H=hp, G1=g1p, G2=g2p)
print(HG1G2m(phase))
print(HG1G2.evaluate(phase, h=hp, g1=g1p, g2=g2p))

# Testing HG12-model
print("HG12-model")
hp = 15*u.mag
g12p = 0.5
phase=10.0*u.deg
HG12m = HG12(H=hp, G12=g12p)
print(HG12m(phase))
print(HG12.evaluate(phase, h=hp, g12=g12p))

# Testing HG12_Pen16-model
print("HG12_Pen16-model")
hp = 15*u.mag
g12p = 0.5
phase=10.0*u.deg
HG12Pm = HG12_Pen16(H=hp, G12=g12p)
print(HG12Pm(phase))
print(HG12_Pen16.evaluate(phase, h=hp, g12=g12p))
```

The output from the above is form me:
> HG-model
> 15.658445486352889 mag
> 15.658445486352889 mag
> HG1G2-model
> 15.595193498596743 mag
> 25.21270286377962 mag
> HG12-model
> 15.590772478433799 mag
> 25.961159874574474 mag
> HG12_Pen16-model
> 15.651920593744613 mag
> 25.891547515825636 mag

**Comment by jianyangli** [comment]
The cause is that the `.evaluate` static method in `HG1G2` class doesn't check the unit of phase angle and convert it to the required unit (rad) before passing to the functions to evaluate Phi1(phase) and Phi2(phase), both of which take values (non-`u.Quantity`) default to radiance as parameters.  `astropy.modeling.Fittable1DModel`, which is the base class of `HG1G2`, takes care of the unit conversion property behind the scene.  But if you directly call `.evaluate` method, then wrong value was passed if phase is in `u.deg`.  Using your code, an example below demonstrates what I mean:

```
import numpy as np
import astropy.units as u
import sbpy
from sbpy.photometry import HG, HG1G2, HG12, HG12_Pen16

# Testing HG1G2-model
print("HG1G2-model")
hp = 15*u.mag
g1p = 0.15
g2p = 0.5
phase=10.0*u.deg
HG1G2m = HG1G2(H=hp, G1=g1p, G2=g2p)
print(HG1G2m(phase))
print(HG1G2.evaluate(phase, h=hp, g1=g1p, g2=g2p))
print(HG1G2.evaluate(phase.value * u.rad, h=hp, g1=g1p, g2=g2p))
print(HG1G2.evaluate(phase.to('rad'), h=hp, g1=g1p, g2=g2p))

# Testing HG12-model
print("HG12-model")
hp = 15*u.mag
g12p = 0.5
phase=10.0*u.deg
HG12m = HG12(H=hp, G12=g12p)
print(HG12m(phase))
print(HG12.evaluate(phase, h=hp, g12=g12p))
print(HG12.evaluate(phase.value * u.rad, h=hp, g12=g12p))
print(HG12.evaluate(phase.to('rad'), h=hp, g12=g12p))

# Testing HG12_Pen16-model
print("HG12_Pen16-model")
hp = 15*u.mag
g12p = 0.5
phase=10.0*u.deg
HG12Pm = HG12_Pen16(H=hp, G12=g12p)
print(HG12Pm(phase))
print(HG12_Pen16.evaluate(phase, h=hp, g12=g12p))
print(HG12_Pen16.evaluate(phase.value * u.rad, h=hp, g12=g12p))
print(HG12_Pen16.evaluate(phase.to('rad'), h=hp, g12=g12p))
```

I have implemented a fix and will submit a pull request.
