### ISSUE TITLE
importing sbpy.activity resulting "cannot create a consistent method resolution order (MRO) for bases type, ABCMeta"

### ISSUE THREAD

**Issue by Yeqzids** [NASA-Planetary-Science/sbpy#312]
**High-level problem description**
Not able to import sbpy.activity.

**What did you do?**
If I do
```
from sbpy.activity import phase_HalleyMarcus, Afrho
```
I am getting
```
TypeError                                 Traceback (most recent call last)
[..]
~/anaconda3/lib/python3.8/site-packages/sbpy/activity/__init__.py in <module>
      4 
      5 from .core import *
----> 6 from .dust import *
      7 from .gas import *

~/anaconda3/lib/python3.8/site-packages/sbpy/activity/dust.py in <module>
    164 
    165 
--> 166 class DustComaQuantityMeta(type(u.SpecificTypeQuantity), abc.ABCMeta):
    167     pass
    168 

TypeError: Cannot create a consistent method resolution
order (MRO) for bases type, ABCMeta
```

**What did you expect?**
The module should load.

**What did really happen?**
See the error message posted above.

**Provide information on your environment:**
operating system and version: [Linux (which distribution?), MacOS, Win] Red Hat 8.5
sbpy version: 0.2.2
astropy version: 5.0
numpy version: 1.21.2

**Comment by Yeqzids** [comment]
I see that issue #234 mentioned the same (similar?) problem and I had run into the same problem before (as noted in issue #239 ), but that issue is closed so I assume it has been fixed?

**Comment by mkelley** [comment]
v0.2.2 requires astropy<4.0.  Try either downgrading astropy, or installing from sbpy's master branch.

**Comment by Yeqzids** [comment]
Thanks Mike, I have gotten it to work. My snippet on colab that used to work is now broken after the upgrade of Horizons API, so I stumbled upon the same problem. I am closing this issue.
