### ISSUE TITLE
Names.parse_comet error for type A and I

### ISSUE THREAD

**Issue by jrob93** [NASA-Planetary-Science/sbpy#332]
**High-level problem description**
The Names.parse_comet function fails for active asteroid (A) and interstellar object types (I)

**What did you do?**
I was trying to use `Names.parse_comet` on the MPC catalogue (https://www.minorplanetcenter.net/iau/MPCORB/CometEls.txt) and noticed that it failed for type A and I objects:
```
from sbpy.data import Names
des = "A/2018 V3" # type fails
# des = "2I/Borisov" # type fails
print(des,Names.parse_comet(des))
```

**What did you expect?**
The snippet should have returned:
```
A/2018 V3 {'type': 'A', 'desig': '2018 V3'}
```
or
```
2I/Borisov {'type': 'I', 'number': 2, 'name': 'Borisov'}
```

**What did really happen?**
```
---------------------------------------------------------------------------
TargetNameParseError                      Traceback (most recent call last)
Input In [13], in <cell line: 4>()
      2 des = "A/2018 V3" # type fails
      3 # des = "2I/Borisov" # type fails
----> 4 print(des,Names.parse_comet(des))

File ~/sbpy/sbpy/data/names.py:373, in Names.parse_comet(s)
    370                 r['name'] = el[5]
    372 if len(r) == 0 or 'type' not in r:
--> 373     raise TargetNameParseError(('{} does not appear to be a '
    374                                 'comet name').format(s))
    375 else:
    376     return r

TargetNameParseError: A/2018 V3 does not appear to be a comet name
```

**Provide information on your environment:**
MacOS Monterey 12.3
sbpy version: 0.3.1
astropy version: 5.0.4
numpy version: 1.22.3

**Comment by jrob93** [comment]
I think this is a simple fix, A & I just need added to the comet-matching pattern which already has PDCX. I've got a PR doing this simple fix and added the two objects above to the `sbpy/data/tests/test_names.py`. However the tests then fail at test_asteroid_or_comet for the asteroid designation "1A", so maybe there's a reason A wasn't being matched before.

(First time contributing, so please let me know if I'm following guidelines okay!)

**Comment by mkelley** [comment]
Thanks for the report.  This is a tricky problem with nomenclature.  Despite being in a cometary orbit, A/ indicates it lacks cometary activity, so I would expect A/ objects to parse as an asteroidal designation.  I think I rely on this behavior in some code to know when to avoid using the "closest apparition" option for JPL Horizons, which only works for comets.  I/ objects may be cometary (2I) or asteroidal (1I), so I would prefer they fail both parse_comet and parse_asteroid, since the target nature is unclear from the name.

**Comment by jrob93** [comment]
Ah okay, makes sense. I'll close the issue and PR then. Cheers!

**Comment by mkelley** [comment]
I'll open an issue in the documentation, which could help others.  Cheers!
