### ISSUE TITLE
Improve weekly test stability

### ISSUE THREAD

**Issue by mkelley** [NASA-Planetary-Science/sbpy#335]
Weekly doc tests fail when JPL SBDB / Horizons updates the absolute magnitude of Ceres, which occurs every month or so.  Being that Ceres is a well-observed object, I suspect it is not a true improvement on the absolute magnitude, but instead a reflection of the method and data sources.  There are several lines of code that need to be updated whenever this happens.

I propose that we find all doc tests that rely on `from_phys` or `from_horizons` for Ceres be skipped or updated to use hard coded values (the latter is preferred).

**Comment by jianyangli** [comment]
OK, I can take care of this.
