### ISSUE TITLE
Website linked to 'latest' documentation

### ISSUE THREAD

**Issue by mkelley** [NASA-Planetary-Science/sbpy#377]
The website is currently linked to the latest documentation.  What I've been noticing is that most users are not installing the latest version, but whatever is available via pip or conda, i.e., the last stable version.  Should we update the sbpy.org link to point to the stable version?  Or, just to sbpy.readthedocs.io and we can configure latest vs. stable on the RTD end (currently it is stable).

**Comment by jianyangli** [comment]
I think it's a good idea to link to the stable version.  Advanced users will find out the latest dev version by themselves if they need.  Most users don't care about the dev version anyway.  Linking to readthedocs website is also fine.  Would the readthedocs website be synced with the version available via pip or conda?

**Comment by jianyangli** [comment]
Why do I see version number [v0.1.dev](https://sbpy.readthedocs.io/en/latest/index.html#) for the latest version?  Shouldn't it be v0.4.dev?

Also, the current version on sbpy.org also needs to be updated to 0.4.

**Comment by mkelley** [comment]
I'm trying to understand that, too.  It might be https://docs.readthedocs.io/en/stable/build-customization.html?highlight=setuptools_scm#avoid-having-a-dirty-git-index which is an issue that astropy also had.

**Comment by mkelley** [comment]
Readthedocs builds stable versions of the documentation whenever a release is tagged in githb.  v0.4 is available there now.

**Comment by mkelley** [comment]
These issues seem to be fixed now: #378
