### ISSUE TITLE
erfa deprecation warning

### ISSUE THREAD

**Issue by wtreach** [NASA-Planetary-Science/sbpy#416]
**High-level problem description**
A warning is issued when importing sbpy, indicating that an astropy call used by sbpy will be deprecated soon. This could make a problem with using sbpy after two minor releases of astropy.

**What did you do?**
A one-line test program:
from sbpy.data import Ephem
Then I get the message:
WARNING: AstropyDeprecationWarning: Importing ErfaWarning from astropy.utils.exceptions was deprecated in version 6.1 and will stop working in a future version. Instead, please use
from erfa import ErfaWarning
 [astropy.utils.exceptions]

**What did you expect?**
No warning message.

**What did really happen?**
The code works fine; this is only an issue for future protability.

**Provide information on your environment:**
operating system and version: MacOS 14.6.1
sbpy @ git+https://github.com/NASA-Planetary-Science/sbpy.git@88ae68b5c4bc7a6d58f848fb40c0d572533c0a6d
astropy version: 6.1.4
numpy version: 1.24.4

**Comment by mkelley** [comment]
👋🏻 @wtreach I'm not able to reproduce this, but I suspect this error actually comes from astroquery.  sbpy only uses ErfaWarning in our testing suite, and it is imported from the recommended package.  What version of astroquery do you use?  This warning was addressed there back in January.  You might want to upgrade astroquery and try again.  I'm using 0.4.7.

**Comment by wtreach** [comment]
@mkelley Looks like you were right! I upgraded astroquery from what I had (0.4.6) to the newest (0.4.7) version. And the error did not occur. It was from just one minor version of astroquery ago :)
