### ISSUE TITLE
Add tests for calculation of Einstein coefficients

### ISSUE THREAD

**Issue by migueldvb** [NASA-Planetary-Science/sbpy#42]
Test that the calculated coefficients for spontaneous emission at 300K agree with the coefficients in the Leiden Atomic and Molecular Database (LAMDA) within a few percent tolerance for a few molecules.  Some remote tests using the [`astroquery.lamda`](https://astroquery.readthedocs.io/en/latest/lamda/lamda.html) package can be included.

**Comment by gianninapr** [comment]
I'll be working on this

**Comment by migueldvb** [comment]
Thanks!
