### ISSUE TITLE
Production rate calculation

### ISSUE THREAD

**Issue by migueldvb** [NASA-Planetary-Science/sbpy#44]
The implementation of production rate calculation from a Haser model (with and w/o photodissociation) can be tested with the published values in table 2 from [this paper](https://arxiv.org/abs/1202.3194). The data is not available in vizier but it can be grabbed from the latex source in the arxiv:
https://arxiv.org/e-print/1202.3194

**Comment by gianninapr** [comment]
We have tests for HCN already. We could also test CH3OH, which I will work on.

**Comment by migueldvb** [comment]
Implemented in #45
