### ISSUE TITLE
numpy import error in astropy-helpers

### ISSUE THREAD

**Issue by mommermi** [NASA-Planetary-Science/sbpy#52]
I tried installing `sbpy` in a clean conda environment (Python 3.6) and stumbled across the missing requirements, which are now fixed in #51.

One problem that still persists is that if you run `setup.py install/develop`, the script will fail since `astropy-helpers` requires `numpy` before the setup routine (which will install `numpy`) is even reached. No big issue for now: simply install `numpy` and the setup script will install the rest.

However, it would be nice to have `numpy` installed automatically, too. Any thoughts on this?

**Comment by migueldvb** [comment]
This may be fixed in `astropy-helpers` 2.0.8 now that `ez_setup.py` is gone. Let me try updating the astropy-helpers submodule and opening a pull request.

**Comment by mkelley** [comment]
Is this still an issue?

**Comment by mommermi** [comment]
So far, nobody has complained, so I guess it's fine. But I can test this tomorrow...

**Comment by jianyangli** [comment]
Just checking back on the existing issues...

Since astropy-helpers is dropped now from the infrastructure, should this issue be dropped as well?

**Comment by mkelley** [comment]
Agreed.
