### ISSUE TITLE
Names class rejects asteroid name "ITA"

### ISSUE THREAD

**Issue by rhiannonlynne** [NASA-Planetary-Science/sbpy#56]
Asteroid 1735 ITA (1948 RJ1) (named "ITA" in the astorb output file) triggers an exception in the Names class. 

```Names.parse_comet('ITA')```

Parsing it as a comet returns {'name': 'ITA'}, but this is a main belt asteroid, and 

```Names.asteroid_or_comet('ITA')``` 

returns 'comet'. 

Just another special case to consider, I guess.

**Comment by mommermi** [comment]
Thanks! This will be fixed in #53. If you find more cases that fail, let us know!
