### ISSUE TITLE
name parsing errors

### ISSUE THREAD

**Issue by rhiannonlynne** [NASA-Planetary-Science/sbpy#57]
Hi Michael - some more examples of names that fail: 
```
V'yus
`I`iwi
`O`o
```

Unicode issues I expect.
(btw, I'm finding these by just loading the MPCORB.DAT file and running all the "readable names" column through sbpy.data.Names .. if you want a utility to read the MPCORB file (which might fit into your Orbits class?) we've got one at 
https://github.com/rhiannonlynne/ssdpu/blob/master/catalog_utils.py which you are welcome to take and presumably modify).

**Comment by rhiannonlynne** [comment]
Ah - also multi-word names don't parse correctly. 
Example:
s = "(2413) van de Hulst"
Names.parse_asteroid(s)
yields 
"Hulst" as the Name.

**Comment by mommermi** [comment]
Ha, life is never as easy as you think... I'll be working on those soon. Thanks for providing the list and the catalog parser. This will probably become a part of `sbpy` soon! Thanks

**Comment by mommermi** [comment]
Ok, they're all fixed (e.g., `{'number': 361267, 'name': '`I`iwi', 'desig': '2006 SV395'}`). If you have some more cases let me know. I'll wait a bit with closing this issue report and merge later.

**Comment by rhiannonlynne** [comment]
Is there a branch I could pull, in order to use the new version? Another name I found to fail (with the older version): 
``Names.parse_asteroid('(20958) A900 MA')``  
I was thinking that the MPC "readable name" ought to be parseable from (20958) A900 MA into 
number: 20958
name: A900 MA 
but I get 
```{'number': 900}```

**Comment by mommermi** [comment]
Yes, you can pull https://github.com/mommermi/sbpy/tree/data

I am not sure about the latest example you provide. SBDB lists `A900 MA` as the designation, but MPC uses `1900 MA`. I will have to ask somebody what is going on here...

**Comment by rhiannonlynne** [comment]
Yeah it seems odd. MPC maybe uses the A instead of the thousand? But why?

**Comment by mommermi** [comment]
Ok, I think I understand it now. That type of designation was used before 1929. The first `A` stands for asteroid - what else...
There is no standardized system - both `A900 MA` and `1900 MA` are perfectly valid. I think I will resort to converting `A900 MA` to `1900 MA`, which is at least compatible with the later designation system. I will some documentation on this. In the end, it doen't really matter which way we go - either one will be incompatible with either MPC or JPL...

**Comment by mommermi** [comment]
@rhiannonlynne Please report future issues directly in #58. Thanks!
