### ISSUE TITLE
Bibliography does not allow multiple references for a single key.

### ISSUE THREAD

**Issue by mkelley** [NASA-Planetary-Science/sbpy#66]
Consider that there are various estimates for the fluorescence band g-factors of CO2, e.g., Crovisier & Encrenaz 1983 vs. Debout et al. 2016.  If we included both in `activity.fluorescence_band_strength` and a user called both to determine the difference, only the last used citation will be tracked.

```python
>>> from sbpy import bib
>>> with bib.Tracking():
>>>     bib.register('task', {'g': 'reference 1'})
>>>     bib.register('task', {'g': 'reference 2'})
>>> print(bib.to_text())
task:
  g: reference 2
```

Perhaps the citations should be internally stored as lists, and new citations appended as needed.

**Comment by mommermi** [comment]
fixed with #75
