### ISSUE TITLE
DataClass does not support masked columns

### ISSUE THREAD

**Issue by mkelley** [NASA-Planetary-Science/sbpy#89]
Seems to be because QTable and Quantity do not support masked columns.

```python
import numpy as np
import astropy.units as u
from astropy.table import QTable

a = np.ma.MaskedArray([1, 2, 3], mask=[True, False, False])
q = a * u.m
tab = QTable(data=[a, q], names=['array', 'quantity'], masked=True)
print(tab)
```
```
array quantity
         m    
----- --------
   --      1.0
    2      2.0
    3      3.0
```

This is presently a problem with `Ephem.from_horizons`, which drops the masks leaving zeros as column values.  For example, it makes comet Encke a naked-eye object:
```
In [115]: print(Ephem.from_horizons('2P', 'designation', closest_apparition=True)[['Tmag', 'Nmag']])
 Tmag Nmag
 mag  mag 
----- ----
20.91  0.0
```

astropy/astropy#1852 looks like the main issue.

**Comment by jianyangli** [comment]
Looks like this is no longer an issue?  My test below looks good to me.

```
In [333]: print(Ephem.from_horizons('2P', 'designation', closest_apparition=True)[['Tmag', 'Nmag']])
<QTable length=1>
  Tmag    Nmag 
  mag     mag  
float64 float64
------- -------
 21.528     ———
```

The related issue in astropy was closed in Apr 2021.  Should we close this issue?

**Comment by mkelley** [comment]
It does seem to work now.  The masking support in astropy is experimental, but I see no reason to keep this issue open.
