### ISSUE TITLE
Test failure from data's field name count

### ISSUE THREAD

**Issue by mkelley** [NASA-Planetary-Science/sbpy#98]
I'm stuck trying to understand this test failure (see also Travis logs).  The code works for me by hand and my local machine cannot reproduce it.  Is there a quick way I can duplicate the environment so that I can reproduce it?

_______________________ test_alternative_name_uniqueness _______________________
    def test_alternative_name_uniqueness():
        """test the uniqueness of alternative field names"""
    
        from ..core import conf
    
>       assert (len(sum(conf.fieldnames, [])) ==
                len(set(sum(conf.fieldnames, []))))
E       AssertionError: assert 133 == 132
E        +  where 133 = len(['targetname', 'id', 'Object', 'Target Identifier', 'i', 'inc', ...])
E        +    where ['targetname', 'id', 'Object', 'Target Identifier', 'i', 'inc', ...] = sum([['targetname', 'id', 'Object', 'Target Identifier'], ['i', 'inc', 'incl', 'Inclination'], ['epoch', 'datetime_jd', 'J...ng Node'], ['w', 'argper', 'Argument of the Periapsis'], ['r', 'rh', 'r_hel', 'heldist', 'Heliocentric Distance'], ...], [])
E        +      where [['targetname', 'id', 'Object', 'Target Identifier'], ['i', 'inc', 'incl', 'Inclination'], ['epoch', 'datetime_jd', 'J...ng Node'], ['w', 'argper', 'Argument of the Periapsis'], ['r', 'rh', 'r_hel', 'heldist', 'Heliocentric Distance'], ...] = <sbpy.data.Conf object at 0x7f036cf2c518>.fieldnames
E        +  and   132 = len({'AZ', 'Altitude', 'Argument of the Periapsis', 'Azimuth', 'D', 'DEC', ...})
E        +    where {'AZ', 'Altitude', 'Argument of the Periapsis', 'Azimuth', 'D', 'DEC', ...} = set(['targetname', 'id', 'Object', 'Target Identifier', 'i', 'inc', ...])
E        +      where ['targetname', 'id', 'Object', 'Target Identifier', 'i', 'inc', ...] = sum([['targetname', 'id', 'Object', 'Target Identifier'], ['i', 'inc', 'incl', 'Inclination'], ['epoch', 'datetime_jd', 'J...ng Node'], ['w', 'argper', 'Argument of the Periapsis'], ['r', 'rh', 'r_hel', 'heldist', 'Heliocentric Distance'], ...], [])
E        +        where [['targetname', 'id', 'Object', 'Target Identifier'], ['i', 'inc', 'incl', 'Inclination'], ['epoch', 'datetime_jd', 'J...ng Node'], ['w', 'argper', 'Argument of the Periapsis'], ['r', 'rh', 'r_hel', 'heldist', 'Heliocentric Distance'], ...] = <sbpy.data.Conf object at 0x7f036cf2c518>.fieldnames
sbpy/data/tests/test_dataclass.py:185: AssertionError
============== 1 failed, 236 passed, 48 skipped in 278.56 seconds ==============

**Comment by mommermi** [comment]
I have seen stuff like this before. It might be that some test function meddles with `conf.fieldnames` in some obscure place - like it does in this exact test function itself. Re-running the test will then make the test fail. Can you replace `test_alternative_name_uniqueness` with this code and then retry?

```
    from ..core import conf

    print(len(sum(conf.fieldnames, [])))
    print(len(set(sum(conf.fieldnames, []))))

    assert (len(sum(conf.fieldnames, [])) ==
            len(set(sum(conf.fieldnames, []))))

    storage = (deepcopy(conf.fieldnames), deepcopy(conf.fieldname_idx))
    conf.fieldnames = [['z', 'a']]
    conf.fieldname_idx = {}

    with pytest.raises(AssertionError):
        # repeat existing fieldname should raise Error
        conf.fieldnames.append(['i'])
        assert (len(sum(conf.fieldnames, [])) ==
                len(set(sum(conf.fieldnames, []))))

    # revert changes to conf.fieldnames
    conf.fieldnames = storage[0]
    conf.fieldname_idx = storage[1]
```

**Comment by mkelley** [comment]
That worked. :1st_place_medal: for @mommermi
